// package.json->
//same configuration files but packagelog.js - detaild configuration

// package.json is the main configuration file of a Node.js project. 
// It contains metadata about the project such as project name, version, description, scripts,
//  and dependencies required to run the application. 
// It is created manually using npm init and can be edited by the developer.

// package-lock.json->
// package-lock.json is automatically generated by npm when dependencies are installed. 
// It stores the exact versions of all installed packages along with their dependencies. 
// This ensures that the same versions are installed every time the project is set up, 
// maintaining consistency across different systems.

// Difference between Dependencies and DevDependencies ->

// Dependencies ->
// Dependencies are the packages required for the application to run properly in production. 
// These are essential for the functioning of the application.
// Example: Express is required to run a web server.

// DevDependencies
// DevDependencies are the packages required only during development. 
// They are not needed when the application is deployed in production.
// Example: Nodemon is used to automatically restart the server during development.